Create and finalize invoice receipts
weareswat/pg-ix-connector pull request #1
Opened 2016-11-17 12:54 UTC by donbonifacio

Booted the project, added CI, and added the logic to create a document based
on the given invoice information. At this moment the client is not updated.

Ref: https://github.com/weareswat/payment-gateway/issues/57

2016-11-17 17:02 UTC, paulosilva86 approved these changes

2016-11-18 10:55 UTC, claudiaalves approved these changes

2016-11-18 11:03 UTC, claudiaalves requested changes

2016-11-18 11:03 UTC, claudiaalves commented on src/pg_ix_connector/core.clj
> +  (str "<invoice_receipt>"
I think you must to use the `:type`here

2016-11-18 11:23 UTC, claudiaalves approved these changes

2016-11-18 11:23 UTC, merged